version: '3.8'

services:
  app:
    container_name: prod-container-flash
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_STREAM_API_KEY: ${NEXT_PUBLIC_STREAM_API_KEY}
        STREAM_SECRET_KEY: ${STREAM_SECRET_KEY}
        NEXT_PUBLIC_STREAM_SECRET_KEY: ${NEXT_PUBLIC_STREAM_SECRET_KEY}
        NEXT_PUBLIC_STREAM_APP_ID: ${NEXT_PUBLIC_STREAM_APP_ID}
        TWOFACTOR_API_KEY: ${TWOFACTOR_API_KEY}
        JWT_KEY: ${JWT_KEY}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_BASE_URL_BACKEND: ${NEXT_PUBLIC_BASE_URL_BACKEND}
        MONGODB_URI: ${MONGODB_URI}
        NEXT_PUBLIC_MIXPANEL_TOKEN: ${NEXT_PUBLIC_MIXPANEL_TOKEN}
        NEXT_PUBLIC_RAZORPAY_KEY_ID: ${NEXT_PUBLIC_RAZORPAY_KEY_ID}
        NEXT_PUBLIC_RAZORPAY_SECRET: ${NEXT_PUBLIC_RAZORPAY_SECRET}
        NEXT_PUBLIC_CASHFREE_CLIENT_ID: ${NEXT_PUBLIC_CASHFREE_CLIENT_ID}
        NEXT_PUBLIC_CASHFREE_CLIENT_SECRET: ${NEXT_PUBLIC_CASHFREE_CLIENT_SECRET}
        NEXT_PUBLIC_HYPERVERGE_APP_ID: ${NEXT_PUBLIC_HYPERVERGE_APP_ID}
        NEXT_PUBLIC_HYPERVERGE_APP_KEY: ${NEXT_PUBLIC_HYPERVERGE_APP_KEY}
        NEXT_PUBLIC_MEASUREMENT_ID: ${NEXT_PUBLIC_MEASUREMENT_ID}
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_FIREBASE_KEY: ${NEXT_PUBLIC_FIREBASE_KEY}
        FIREBASE_SERVICE_ACCOUNT_BASE64: ${FIREBASE_SERVICE_ACCOUNT_BASE64}
    image: flashcallme/flashcall:prod
    ports:
      - "3000:3000"

    env_file:
      - .env.production

    # For production, avoid mounting volumes if not needed
    # volumes:
    #   - .:/app

    command: npm start