export enum QUERY_KEYS {
	GET_CREATOR = "get_creator",
	GET_CREATOR_DISCOUNT_SERVICES = "get_creator_discount_services",
	GET_CREATOR_AVAILABILITY_SERVICES = "get_creator_availability_services",
	GET_CREATORS = "get_creators",
	GET_CLIENTS = "get_clients",
	GET_CREATOR_FEEDBACKS = "get_creator_feedbacks",
	GET_USER_TRANSACTIONS = "get_user_transactions",
	GET_USER_CALLS = "get_user_calls",
	GET_USER_SCHEDULED_CALLS = "get_user_scheduled_calls",
	GET_USER_FAVORITES = "get_user_favorites",
	GET_BLOCKED_CLIENTS = "get_blocked_clients",
	GET_CREATOR_NOTIFICATION = "get_creator_notification",
	GET_USER_AVAILABILITY = "get_user_availability",
	GET_USER_REFERRALS = "get_user_referrals",
	GET_CREATOR_GROUPS = "get_creator_groups",
	GET_GROUP_MEMBERS = "get_group_members",
	GET_CREATOR_CLIENTS = "get_creator_clients",
	GET_CREATOR_TEMPLATES = "get_creator_templates",
	GET_CREATOR_CAMPAIGNS = "get_creator_campaigns",
	GET_UNIQUE_CLIENTS = "get_unique_clients",
	GET_CALLS_BY_CLIENTID_AND_CREATORID = "get_calls_by_clientId_and_creatorId",
	GET_NOTES = "get_notes",
}
